accountbook/accountbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountbook/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('consume/', views.consume, name='consume'),
    path('<int:account_pk>/', views.detail, name='detail')
]

accountbook/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

accountbook/main/models.py
from django.db import models

# Create your models here.

class Consume(models.Model):
    date = models.DateField()
    cost = models.IntegerField()
    main_category = models.CharField(max_length=15)
    sub_category = models.CharField(max_length=15)
    detail = models.CharField(max_length=20)
    DC = models.BooleanField(default=False)
    fixed_expenses = models.BooleanField(default=False)
    image = models.ImageField(blank=True)

    def __str__(self):
        return self.detail

accountbook/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

accountbook/main/forms.py
from django import forms
from .models import Consume

class Consumeform(forms.ModelForm):

    class Meta:
        model = Consume
        fields = '__all__'
        # exclude = ('title',)

accountbook/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

accountbook/main/views.py
from django.shortcuts import render, redirect
from .forms import Consumeform
from .models import Consume

# Create your views here.
def index(request):
    log = str(request.user)
    if log == 'AnonymousUser':
        return redirect('users:login')
    
    else:
        account_list = Consume.objects.all()
        context = {
            'account_list' : account_list
        }

    return render(request, 'main/index.html', context)

def consume(request):
    if request.method == 'POST':
        form = Consumeform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main:index')
    
    else:
        form = Consumeform()
        context = {
            'form': form
        }

    return render(request, 'main/consume.html', context)

def detail(request, account_pk):
    account = Consume.objects.get(pk=account_pk)
    context = {
        'account' : account
    }
    return render(request, 'main/detail.html', context)

accountbook/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model, login as auth_login, logout as auth_logout

# Create your views here.
User = get_user_model()

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('main:index')
    
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form.as_p,
    }
    return render(request, 'users/form.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('main:index')
    
    else:
        form = AuthenticationForm()
    
    context ={
        'form':form.as_p()
    }

    return render(request, 'users/form.html', context)


def logout(request):
    auth_logout(request)
    return redirect('users:login')

accountbook/main/templates/main/add.html
{% extends 'base.html' %}

{% block title %}
  <title>add</title>
{% endblock title %}

{% block contents %}

<h1>ADD</h1>

{% endblock contents %}

accountbook/main/templates/main/consume.html
{% extends 'base.html' %}

{% block title %}
  <title>add</title>
{% endblock title %}

{% block contents %}

  <h1>소비내역 입력</h1>
  <form action="{% url 'main:consume' %}" method='POST' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="소비내역 입력">
  </form>

{% endblock contents %}

accountbook/main/templates/main/detail.html
{% extends 'base.html' %}

{% block title %}
<title> {{ account.pk }} 내역 </title>
{% endblock title %}


{% block contents %}

<h1>detail PAGE</h1>

<ul>
  <li> {{ account.detail }} </li>
  <li> {{ account.date }} </li>
  <li> {{ account.main_category }} </li>
  <li> {{ account.sub_category }} </li>
</ul>

{% if account.image %}
  <img src="{{ account.image.url }}" alt="">
{% endif %}


{% endblock contents %}

accountbook/main/templates/main/index.html
{% extends 'base.html' %}

{% block title %}
  <title>index</title>
{% endblock title %}

{% block contents %}

<h1>INDEX</h1>

{% for account in account_list %}

  <p> {{ account.pk }} 번째 내역 </p>

  <a href="{% url 'main:detail' account.pk %}"> {{ account.detail }} </a>
  
  <p> {{ account.date }} </p>
  
  {% if account.image %}
  <img src="{{ account.image.url }}" alt="{{ account.detail }}">
  {% endif %}

  <hr>

{% empty %}

  <h1> 입력된 내역이 없습니다 </h1>

{% endfor %}

<a href={% url 'users:logout' %}>log out</a>

<br>

<a href={% url 'main:consume' %}>Consume init</a>

{% endblock contents %}

accountbook/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  {% block title %}
  
  {% endblock  %}
</head>
<body>
  {% block contents %}
  
  {% endblock contents %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

accountbook/users/templates/users/form.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
  <title>form</title>
{% endblock title %}

{% block contents %}

  {% if request.resolver_match.url_name == 'login' %}
    <h1>Login Page</h1>
  {% elif request.resolver_match.url_name == 'signup' %}
    <h1>Sign Up</h1>
  {% endif %}
  
  {% if request.resolver_match.url_name == 'login' %}
  <form action="{% url 'users:login' %}" method="POST">
  {% elif request.resolver_match.url_name == 'signup' %}
  <form action="{% url 'users:signup' %}" method="POST">
  {% endif %}

    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>

  {% if request.resolver_match.url_name == 'login' %}
  <a href="{% url 'users:signup' %}">sign up</a>
  <hr>
  <img src="{% static '쨍이.jpg' %}" alt="쨍이">
  {% elif request.resolver_match.url_name == 'signup' %}
  <a href="{% url 'users:login' %}">log in</a>
  <hr>
  <img src="{% static 'main/메건.jpg' %}" alt="나꼬">
  <img src="{% static 'users/빵이.jpg' %}" alt="빵이">
  <img src="{% static 'users/쨍이.jpg' %}" alt="쨍이">
  {% endif %}

{% endblock contents %}